config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users do
    collection do
      post '/follow/:id', action: :follow, controller: :follows, as: :follow
      post '/unfollow/:id', action: :unfollow, controller: :follows, as: :unfollow
    end
  end

  resources :posts

  resources :notifications, only: :index do
    put '/read_all', action: :read_all, on: :collection
  end

  resources :home, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post
    can :manage, Post, user_id: user && user.id
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :followed_id, uniqueness: { scope: :follower_id }
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  def viewed?
    viewed
  end

  def self.read_all!
    update_all(viewed: true)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged]

  belongs_to :user

  validates :text, presence: true
  validates :title, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :nickname

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :nickname, presence: true, uniqueness: true
  validates :email, presence: true

  has_many :follow_followers, class_name: 'Follow', foreign_key: :followed_id
  has_many :follow_followed, class_name: 'Follow', foreign_key: :follower_id

  has_many :notifications,
           class_name: 'Notification',
           foreign_key: :receiver_id,
           dependent: :destroy

  has_many :send_notifications,
           class_name: 'Notification',
           foreign_key: :sender_id,
           dependent: :destroy

  has_many :posts, dependent: :destroy

  has_many :followers, through: :follow_followers
  has_many :following, through: :follow_followed, source: :followed


  def unread_notifications?
    notifications.exists?(viewed: false)
  end

  def follow(user)
    following << user
    notify_follow(user)
  end

  def unfollow(user)
    following.delete(user)
  end

  private

  def notify_follow(receiver)
    UserFollowNotifier.new(self, receiver).save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_filter :authenticate_user!

  def follow
    current_user.follow(user)
    redirect_to :back
  end

  def unfollow
    current_user.unfollow(user)
    redirect_to :back
  end

  private


  def user
    @user ||= User.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @search = HomePresenter.new(params[:text])
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @notifications = current_user.notifications
  end

  def read_all
    current_user.notifications.read_all!
    head 200
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  authorize_resource

  def index
    @posts = Post.all.collect { |post| PostPresenter.new(post) }
  end

  def show
    @post = PostPresenter.new(@post)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params.merge(user: current_user))
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post ||= Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) do |devise_params|
      devise_params.permit(:name, :nickname, :email, :password,
                           :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |devise_params|
      devise_params.permit(:name, :nickname, :email, :password,
                           :password_confirmation, :current_password)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.map { |user| UserPresenter.new(user) }
  end

  def show
    @user = UserPresenter.new(user)
  end

  private

  def user
    User.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(user, size = 80)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?size=#{size}"
  end
end

app/views/home/index.html.erb
<div class="row">
  <h3><%= t 'users' %></h3>
  <div class="large-9 columns" role="content">
    <% @search.users.each do |user| %>
      <article>
        <h3><%= link_to user.name, user_path(user) %></h3>
          <div class="row">
            <div class="large-2 columns">
              <%= image_tag gravatar_url(user) %>
            </div>
            <div class="large-10 columns">
              <%= t 'nickname' %>: <%= user.nickname %><br/>
              <%= t 'posts' %>: <%= user.posts_count %><br/>
            </div>
         </div>
       </article>
       <hr/>
     <% end %>
  </div>
</div>

<div class="row">
  <h3><%= t 'posts' %></h3>
  <div class="large-9 columns" role="content">
    <% @search.posts.each do |post| %>
      <article>
        <h3><%= link_to post.title, post_path(post) %></h3>
        <h6><%= t 'written_by' %>
          <a href="#">
            <%= link_to post.user_name, user_path(post.user) %>
          </a> <%= t('when') %>
          <%= post.formatted_date %>.
        </h6>
          <div class="row">
            <div class="large-2 columns">
              <%= image_tag gravatar_url(post.user) %>
            </div>
            <div class="large-10 columns">
              <%= truncate(post.sanitized_text, length: 500) {
                link_to(post.omit_text_with, post_path(post))
              } %>
            </div>
         </div>
       </article>
       <hr/>
     <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <div class="top-bar-section">
    <ul class="left">
      <li class="name"><%= link_to t('users'), users_path %></li>
      <li class="name"><%= link_to t('posts'), posts_path %></li>
      <li class="has-form">
        <div class="row collapse">
          <form action="/home" method="get">
            <div class="large-8 small-9 columns">
              <input type="text" name="text" placeholder="<%= t 'search' %>">
            </div>
            <div class="large-4 small-3 columns">
              <input type="submit" href="#" class="alert button expand" value="<%= t 'search' %>"></input>
            </div>
          </form>
        </div>
      </li>
    </ul>
  </div>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to t('home'), root_path%></li>
<% if user_signed_in? %>
  <li>
    <%= link_to t('notifications'), notifications_path %>
    <% if current_user.unread_notifications? %>
      <small class="notification"></small>
    <% end %>
  </li>
  <li><%= link_to t('edit_account'), edit_user_registration_path %></li>
  <li><%= link_to t('sign_out'), destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to t('sign_in'), new_user_session_path %></li>
  <li><%= link_to t('sign_up'), new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t('app_name') %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : t('app_name') %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
        <div class="large-6 columns">
          <p><%= t 'copyright' %></p>
      </div>
    </div>
  </footer>
</html>

app/views/notifications/index.html.erb
<div class="row">
  <h3> <%= t 'notifications' %> </h3>
  <% if @notifications.empty? %>
    <hr/>
    <h5> <%= t 'without_notifications' %> </h5>
  <% end %>
  <div class="large-9 columns" role="content">
    <% @notifications.each do |notification| %>
      <hr/>
      <div class="row">
        <div class="large-9 columns">
          <%= notification.created_at %> -
          <%= t(notification.model + '_message',
                user_name: link_to(notification.sender.name,
                                   user_path(notification.sender))
               ).html_safe %>
          <br/>
        </div>
      </div>
     <% end %>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function () {
  $.ajax({
    url: '/notifications/read_all',
    type: "PUT",
  });
});
</script>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <div class="field">
    <%= f.input :title %>
  </div>
  <div class="field">
    <%= f.input :text, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'mini'} } %>
  </div>
  <div class="actions">
    <%= f.submit t('save'), :class => 'button right' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1><%= t 'edit' %> <%= t 'post' %></h1>

<%= render 'form' %>

<%= link_to t('back'), posts_path %>

app/views/posts/index.html.erb
<div class="row">
  <h3><%= t 'posts' %></h3>
  <div class="large-9 columns" role="content">
    <% @posts.each do |post| %>
      <article>
        <h3><%= link_to post.title, post_path(post) %></h3>
        <h6><%= t 'written_by' %>
          <a href="#">
            <%= link_to post.user_name, user_path(post.user) %>
          </a> <%= t('when') %>
          <%= post.formatted_date %>.
        </h6>
          <div class="row">
            <div class="large-2 columns">
              <%= image_tag gravatar_url(post.user) %>
            </div>
            <div class="large-10 columns">
              <%= truncate(post.sanitized_text, length: 500) {
                link_to(post.omit_text_with, post_path(post))
              } %>
            </div>
         </div>
       </article>
       <hr/>
     <% end %>
     <% if user_signed_in? %>
       <%= button_to t('new'), new_post_path, method: :get, class: 'button right' %>
     <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1><%= t 'new' %> <%= t 'post' %></h1>

<%= render 'form' %>

<%= link_to t('back'), posts_path %>

app/views/posts/show.html.erb
<div class="row">
  <div class="large-9 columns" role="content">
    <article>
      <h3><%= @post.title %></h3>
        <div class="row">
          <div class="large-12 columns">
            <%= @post.text.html_safe %>
          </div>
       </div>
     </article>
     <hr/>
     <div class="text-center">
        <%= image_tag gravatar_url(@post.user) %>
        <h6><%= t 'written_by' %>
          <a href="#">
            <%= link_to @post.user.name, user_path(@post.user) %>
          </a> <%= t 'when' %>
          <%= @post.formatted_date %>.
        </h6>
        <% if can? :manage, @post.post %>
          <%= button_to t('edit'), edit_post_path(@post), method: :get, class: 'button left' %>
          <%= button_to t('delete'), post_path(@post), method: :delete, class: 'button right' %>
        <% end %>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="large-9 columns" role="content">
    <% @users.each do |user| %>
      <article>
        <h3><%= link_to user.name, user_path(user) %></h3>
          <div class="row">
            <div class="large-2 columns">
              <%= image_tag gravatar_url(user) %>
            </div>
            <div class="large-10 columns">
              <%= t 'nickname' %>: <%= user.nickname %><br/>
              <%= t 'posts' %>: <%= user.posts_count %><br/>
            </div>
         </div>
       </article>
       <hr/>
     <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="large-9 push-3 columns">
    <% @user.posts.each do |post|   %>
      <h3><%= link_to post.title, post_path(post) %></h3>
      <p>
        <%= truncate(post.sanitized_text, length: 500) {
          link_to(post.omit_text_with, post_path(post))
        } %>
      </p>
    <% end %>
  </div>
  <div class="large-3 pull-9 columns">
    <h1><%= image_tag gravatar_url(@user, 200) %></h1>
    <% if user_signed_in? %>
        <%= @user.follow_or_unfollow_link(current_user) %>
    <% end %>
    <h5> <%= t 'name' %>: <%= @user.name %> </h5>
    <h5> <%= t 'nickname' %>: <%= @user.nickname %> </h5>
    <h5> <%= t 'posts' %>: <%= @user.posts_count %> </h5>
    <div>
      <h5><b><%= t 'following' %></b></h5>
      <br/>
      <%= t 'nobody' if @user.following.empty? %>
      <% @user.following.each do |user| %>
        <%= link_to image_tag(gravatar_url(user, 40), class: 'user-icon'), user_path(user) %>
      <% end %>
    </div>
    <br/>
    <div>
      <h5><b><%= t 'followers' %></b></h5>
      <br/>
      <%= t 'nobody' if @user.followers.empty? %>
      <% @user.followers.each do |user| %>
        <%= link_to image_tag(gravatar_url(user, 40), class: 'user-icon'), user_path(user) %>
      <% end %>
    </div>
  </div>
</div>